version: "3.8"

# we use network_mode: bridge to use the default network rather than creating a new network

services:
  app:
    image: localhost:5000/prefect-example:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PREFECT__CLOUD__API_KEY
      - PREFECT__CONTEXT__FLOW_RUN_ID
    network_mode: bridge
    command: ['prefect', 'execute', 'flow-run']
